import Foundation

/// A constructed before/after pair for the demo and the article.
///
/// Nothing here was generated by a real `swift build --sbom-spec cyclonedx`
/// run: the shapes (bom-ref, purl, pedigree, `swift-entity`, the
/// package → product → product edge layout) follow SE-0509's own examples,
/// but the packages, versions, SHAs and the two `example-*` organisations are
/// made up. The scenario: a coding agent's PR titled "Retry image loads on
/// flaky networks" that also, along the way, fixed a logging build error by
/// pointing `swift-log` at a fork, bumped `swift-crypto` to clear a
/// deprecation, and reused a snapshot helper from app code.
public enum SampleSBOMs {

    public static let root = "storefront"

    // MARK: Documents

    public static let base: CycloneDXDocument = document(
        packages: [
            pkg("swift-collections", "github.com/apple/swift-collections", "1.1.4"),
            pkg("swift-log", "github.com/apple/swift-log", "1.6.1"),
            pkg("swift-crypto", "github.com/apple/swift-crypto", "3.8.0"),
            pkg("swift-asn1", "github.com/apple/swift-asn1", "1.3.0"),
            pkg("swift-snapshot-testing", "github.com/pointfreeco/swift-snapshot-testing", "1.17.4"),
            pkg("storefront-design", "github.com/storefront-inc/storefront-design", "2.3.0"),
        ],
        products: [
            ("swift-collections", "Collections"), ("swift-log", "Logging"),
            ("swift-crypto", "Crypto"), ("swift-crypto", "_CryptoExtras"),
            ("swift-asn1", "SwiftASN1"), ("swift-snapshot-testing", "SnapshotTesting"),
            ("storefront-design", "DesignSystem"),
        ],
        productEdges: [
            "storefront:StorefrontKit": [
                "swift-collections:Collections", "swift-log:Logging",
                "swift-crypto:_CryptoExtras", "storefront-design:DesignSystem",
            ],
            "swift-crypto:_CryptoExtras": ["swift-asn1:SwiftASN1"],
        ],
        tool: "6.4.0"
    )

    public static let head: CycloneDXDocument = document(
        packages: [
            pkg("swift-collections", "github.com/apple/swift-collections", "1.1.4"),
            pkg("swift-log", "github.com/example-forks/swift-log", forkSHA),
            pkg("swift-crypto", "github.com/apple/swift-crypto", "4.0.0"),
            pkg("swift-asn1", "github.com/apple/swift-asn1", "1.4.0"),
            pkg("swift-snapshot-testing", "github.com/pointfreeco/swift-snapshot-testing", "1.17.4"),
            pkg("storefront-design", "github.com/storefront-inc/storefront-design", "2.3.0"),
            pkg("swift-async-algorithms", "github.com/apple/swift-async-algorithms", "1.0.4"),
            pkg("retry-kit", "github.com/example-labs/retry-kit", "0.3.1"),
        ],
        products: [
            ("swift-collections", "Collections"), ("swift-log", "Logging"),
            ("swift-crypto", "Crypto"), ("swift-crypto", "_CryptoExtras"),
            ("swift-asn1", "SwiftASN1"), ("swift-snapshot-testing", "SnapshotTesting"),
            ("storefront-design", "DesignSystem"),
            ("swift-async-algorithms", "AsyncAlgorithms"), ("retry-kit", "RetryKit"),
        ],
        productEdges: [
            "storefront:StorefrontKit": [
                "swift-collections:Collections", "swift-log:Logging",
                "swift-crypto:_CryptoExtras", "storefront-design:DesignSystem",
                "swift-async-algorithms:AsyncAlgorithms", "retry-kit:RetryKit",
                "swift-snapshot-testing:SnapshotTesting",
            ],
            "swift-crypto:_CryptoExtras": ["swift-asn1:SwiftASN1"],
        ],
        tool: "6.4.0"
    )

    /// The lockfiles for the same two commits.
    public static let baseResolved = ResolvedFile(pins: [
        pin("swift-collections", "https://github.com/apple/swift-collections.git", "1.1.4", "a1"),
        pin("swift-log", "https://github.com/apple/swift-log.git", "1.6.1", "b1"),
        pin("swift-crypto", "https://github.com/apple/swift-crypto.git", "3.8.0", "c1"),
        pin("swift-asn1", "https://github.com/apple/swift-asn1.git", "1.3.0", "d1"),
        pin("swift-snapshot-testing", "https://github.com/pointfreeco/swift-snapshot-testing", "1.17.4", "e1"),
        pin("storefront-design", "https://github.com/storefront-inc/storefront-design.git", "2.3.0", "f1"),
    ])

    public static let headResolved = ResolvedFile(pins: [
        pin("swift-collections", "https://github.com/apple/swift-collections.git", "1.1.4", "a1"),
        ResolvedFile.Pin(identity: "swift-log", location: "https://github.com/example-forks/swift-log.git",
                         state: .init(revision: forkSHA, version: nil, branch: "fix-strict-concurrency")),
        pin("swift-crypto", "https://github.com/apple/swift-crypto.git", "4.0.0", "c2"),
        pin("swift-asn1", "https://github.com/apple/swift-asn1.git", "1.4.0", "d2"),
        pin("swift-snapshot-testing", "https://github.com/pointfreeco/swift-snapshot-testing", "1.17.4", "e1"),
        pin("storefront-design", "https://github.com/storefront-inc/storefront-design.git", "2.3.0", "f1"),
        pin("swift-async-algorithms", "https://github.com/apple/swift-async-algorithms.git", "1.0.4", "g1"),
        pin("retry-kit", "https://github.com/example-labs/retry-kit.git", "0.3.1", "h1"),
    ])

    public static var baseJSON: String { encode(base) }
    public static var headJSON: String { encode(head) }

    // MARK: Builders

    static let forkSHA = "9f2c41d07be3a8e5c6d1f0a2b4c8e7d6a5b3f1e0"

    typealias PackageSpec = (identity: String, source: String, version: String)

    static func pkg(_ identity: String, _ source: String, _ version: String) -> PackageSpec {
        (identity, source, version)
    }

    static func pin(_ identity: String, _ location: String, _ version: String, _ tag: String) -> ResolvedFile.Pin {
        // Deterministic fake revision per (identity, tag) so equal pins compare equal.
        let revision = String(repeating: tag, count: 20)
        return ResolvedFile.Pin(identity: identity, location: location,
                                state: .init(revision: revision, version: version))
    }

    static func document(
        packages: [PackageSpec],
        products: [(String, String)],
        productEdges: [String: [String]],
        tool: String
    ) -> CycloneDXDocument {
        let versionOf = Dictionary(packages.map { ($0.identity, $0) }, uniquingKeysWith: { a, _ in a })
        var components: [CycloneDXDocument.Component] = []
        for p in packages {
            components.append(.init(
                bomRef: p.identity, name: p.identity, version: p.version,
                purl: "pkg:swift/\(p.source)@\(p.version)",
                pedigree: .init(commits: [.init(uid: nil, url: "https://\(p.source).git")]),
                properties: [.init(name: "swift-entity", value: "swift-package")]))
        }
        for (owner, product) in products {
            guard let spec = versionOf[owner] else { continue }
            components.append(.init(
                bomRef: "\(owner):\(product)", name: product, version: spec.version,
                purl: "pkg:swift/\(spec.source):\(product)@\(spec.version)",
                properties: [.init(name: "swift-entity", value: "swift-product")]))
        }

        var deps: [CycloneDXDocument.Dependency] = []
        // Root package → its own product and every package in the resolved graph.
        deps.append(.init(ref: root, dependsOn: ["\(root):StorefrontKit"] + packages.map(\.identity)))
        // Each package → the products it vends.
        for p in packages {
            let vended = products.filter { $0.0 == p.identity }.map { "\($0.0):\($0.1)" }
            deps.append(.init(ref: p.identity, dependsOn: vended))
        }
        for (from, to) in productEdges.sorted(by: { $0.key < $1.key }) {
            deps.append(.init(ref: from, dependsOn: to))
        }

        let rootComponent = CycloneDXDocument.Component(
            bomRef: root, name: root, version: "5.12.0",
            purl: "pkg:swift/github.com/storefront-inc/storefront@5.12.0", type: "application",
            properties: [.init(name: "swift-entity", value: "swift-package")])
        let toolComponent = CycloneDXDocument.Component(
            bomRef: "urn:uuid:swiftpm", name: "swift-package-manager", version: tool,
            purl: "pkg:swift/github.com/swiftlang/swift-package-manager@\(tool)",
            scope: "excluded", type: "application")

        return CycloneDXDocument(
            specVersion: "1.7",
            metadata: .init(timestamp: "2026-09-24T00:00:00Z",
                            tools: .init(components: [toolComponent]),
                            component: rootComponent),
            components: components,
            dependencies: deps)
    }

    static func encode(_ doc: CycloneDXDocument) -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        guard let data = try? encoder.encode(doc), let text = String(data: data, encoding: .utf8) else {
            return "{}"
        }
        return text
    }
}
